# ONLY RESULTS THAT CAN BE GENERATED BY ROLLING THE GENESYS DICE
boost = ["","","X","XA","AA","A"]
setback = [ "", "", "F", "F", "T", "T" ]
ability = [ "", "X", "X", "XX", "A", "A", "XA", "AA" ]
difficulty =  [ "", "F", "FF", "T", "T", "T", "TT", "FT" ]
proficiency = [ "", "X", "X", "XX", "XX", "A", "XA", "XA", "XA", "AA", "AA", "TP" ]
challenge = [ "", "F", "F", "FF", "FF", "T", "T", "FT", "FT", "TT", "TT", "DR" ]